lidi/home/urls.py
from django.conf.urls import url
from . import views


app_name = 'home'

urlpatterns = [
    # /problems/
    url(r'^$', views.index, name="index"),
]

lidi/lidi/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import TemplateView

app_name = 'lidi'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include('login.urls')),
    url(r'^problems/', include('problem.urls')),
    url(r'^upload/', include('upload.urls')),
    url(r'^signup/', include('signup.urls')),
    url(r'^statistics/', include('statistics.urls')),
    url(r'^', include('home.urls')),
]

lidi/login/urls.py
from django.conf.urls import url

from . import views

app_name = 'login'

urlpatterns = [
    # /login/
    url(r'^$', views.index, name="index"),

    # /login/out/
    url(r'^out/$', views.logout, name="logout"),

    # /login/reset_password/<conf_link>/
    url(r'^reset_password/(?P<conf_link>\d+)$', views.reset_password, name='reset_password'),

    # /login/reset_password/
    url(r'^reset_password/$', views.reset_password, name='reset_password')
]

lidi/problem/urls.py
from django.conf.urls import url

from . import views


app_name = 'problem'

urlpatterns = [
    # /problems/
    url(r'^$', views.index, name="index"),
    
    # /problems?page=<page>/
    url(r'^\\?page=(?P<page>[0-9]+)/$', views.index, name="index"),

    # /problems?page=<page>?sort=<sort_by>/
    url(r'^\\?page=(?P<page>[0-9]+)\\?sort=(?P<sort_by>[\s\S]+)/$', views.index, name="index"),

    # /problems/<problem_id>/
    url(r'^(?P<problem_id>[0-9]+)/$', views.detail, name="detail"),
]

lidi/signup/urls.py
from django.conf.urls import url

from . import views

app_name = 'signup'

urlpatterns = [
    # /signup/
    url(r'^$', views.index, name="index"),

    # /signup/confirm/<conf_link>/
    url(r'^confirm/(?P<conf_link>\d+)$', views.confirm, name='confirm'),
]

lidi/statistics/urls.py
from django.conf.urls import url

from . import views

app_name = 'statistics'

urlpatterns = [
    # /statistics/
    url(r'^$', views.index, name='index'),

    # /statistics/problem/
    url(r'^problem/$', views.problem, name='problem'),

    # /statistics/problem/<problem_id>/
    url(r'^problem/(?P<problem_id>\d+)/$', views.problem, name='problem_detail'),

    # /statistics/country/
    url(r'^country/$', views.country, name='country'),

    # /statistics/country/<country_slug>/
    url(r'^country/(?P<country_slug>[a-z_]+)/$', views.country, name='country_detail'),

    # /statistics/users/
    url(r'^users/$', views.users, name='users'),

    # /statistics/users/<username>
    url(r'^users/(?P<username>[0-9a-zA-Z_]+)/$', views.users, name='users_detail'),

    # /statistics/achievements/
    url(r'^achievements/$', views.achievements, name='achievements'),

    # /statistics/achievements/<achievement_id>/
    url(r'^achievements/(?P<achievement_id>\d+)/$', views.achievements, name='achievements_detail')
]

lidi/upload/urls.py
from django.conf.urls import url

from . import views

app_name = 'upload'

urlpatterns = [
    # /upload/
    url(r'^$', views.upload_file, name="upload"),
]

lidi/problem/models.py
from datetime import date

from django.db import models

import signup


class Problem(models.Model):
    name = models.CharField(max_length=200)
    desc = models.CharField(max_length=6000)
    difficulty = models.IntegerField()
    submitted_by = models.ForeignKey(signup.models.User, related_name='submitted_by')
    submitted_on = models.CharField(max_length=10, default='{0}-{1}-{2}'.format(date.today().year, date.today().month, date.today().day))
    solved_by_how_many = models.IntegerField(default=0)
    first_solved_by = models.ForeignKey(signup.models.User, related_name='first_solved_by', null=True)
    first_solved_on = models.DateField(null=True)
    last_successful_try = models.DateField(null=True)

    def __str__(self):
        return self.name


class Submission(models.Model):
    user = models.ForeignKey(signup.models.User)
    problem = models.ForeignKey(Problem)
    date = models.CharField(max_length=10, default='{0}-{1}-{2}'.format(date.today().year, date.today().month, date.today().day))
    tries = models.IntegerField(default=0)
    tries_until_correct = models.IntegerField(default=0)
    grade = models.IntegerField(default=-1)
    sub_file = models.CharField(max_length=100)

    def __str__(self):
        return '{0} - {1}'.format(self.user, self.problem)

lidi/problem/forms.py
from django import forms
from signup.models import ProgrammingLanguage


class UploadSolutionForm(forms.Form):
    f = forms.FileField(label='', widget=forms.FileInput(attrs={'class': 'upload_file_button'}))
    prog_lang = forms.ModelChoiceField(queryset=ProgrammingLanguage.objects.all().order_by('name'), label="", \
                                       help_text="", empty_label='Programming language')

lidi/problem/views.py
from django.shortcuts import render, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import HttpResponse, Http404

from .models import Problem, Submission
from signup.models import User
from .forms import UploadSolutionForm
from .support import handle_solution, get_solutions_and_times


def index(request, page=1, sort_by='id'):
    """
        Loads a page with the list of problems. It supports pagination.
        :param request
        :param page: page of pagination of problems
        :param sort_by: what column do we want to sort by
    """

    # Get all problems.
    all_problems = list(Problem.objects.all().order_by(sort_by))

    # If there are none, return basic HttpResponse.
    if not all_problems:
        return HttpResponse("Empty db")

    # Check if user variable is stored in session. If not, set the variable to None.
    try:
        request.session['user']
    except KeyError:
        request.session['user'] = None

    # If user is logged in, get his submissions to add user's results to the problems table.
    if request.session['user'] is not None:
        user_submissions = Submission.objects.filter(user=User.objects.get(username=request.session['user']))
        for i, problem in enumerate(all_problems):
            user_grade = -1  # if user has not tried the problem
            for user_submission in user_submissions:
                if problem == user_submission.problem:
                    user_grade = user_submission.grade
                    break
            all_problems[i] = problem.__dict__
            all_problems[i]['user_grade'] = user_grade

    # View all problems at once, without pagination.
    if page == 0:
        return render(request, 'problem/index.html', {'problems': all_problems, 'user': request.session['user']})

    paginator = Paginator(all_problems, 1)
    try:  # return the proper page
        problems = paginator.page(page)
    except PageNotAnInteger:
        problems = paginator.page(1)
    except EmptyPage:  # if page is out of range, return the last page
        return redirect('problem:index', page=paginator.num_pages, sort_by=sort_by)

    return render(request, 'problem/index.html', {'problems': problems, 'user': request.session['user']})


def detail(request, problem_id):
    """
        Loads a page with details of desired problem.
        :param request
        :param problem_id: id of problem user want to see details for
    """

    # Get the details of problem. If problem with id problem_id does not exist, raise 404.
    try:
        problem = Problem.objects.get(pk=problem_id)
    except Problem.DoesNotExist:
        raise Http404("Problem with given id does not exist.")

    l_grade = -1
    h_grade = -1
    out_time = -1

    # Get possible data about user's previous submissions.
    try:
        user = User.objects.get(username=request.session['user'])
        user_id = user.id
        submission = Submission.objects.get(user=user_id, problem=problem_id)
        h_grade = submission.grade
        out_time = get_solutions_and_times(request.session['user'], problem_id)
    except KeyError:  # user is not logged in
        request.session['user'] = None
    except ObjectDoesNotExist:  # if no submissions, do nothing
        pass
    finally:
        if user:
            request.session['user_category'] = user.category_id
        else:
            request.session['user_category'] = None

    # If user submitted the program, we need to handle that.
    if request.method == 'POST':
        form = UploadSolutionForm(request.POST, request.FILES)
        if form.is_valid():
            if request.session['user'] is not None:
                l_grade, h_grade, error = handle_solution(request.FILES['f'], problem_id, request.session['user'],
                                                          form.cleaned_data['prog_lang'].name.strip())
                out_time = get_solutions_and_times(request.session['user'], problem_id)
                return render(request, 'problem/detail.html', {'problem': problem, 'form': form, 'user': request.session['user'],
                                                               'grade': h_grade, 'l_grade': l_grade, 'error': error,
                                                               'out_time': out_time,
                                                               'user_category': request.session['user_category']})
            else:
                return HttpResponse("Please login")
    else:
        form = UploadSolutionForm()

    return render(request, 'problem/detail.html', {'problem': problem, 'form': form, 'user': request.session['user'],
                                                   'grade': h_grade, 'l_grade': l_grade, 'error': -1,
                                                   'out_time': out_time,
                                                   'user_category': request.session['user_category']})

lidi/problem/templates/problem/detail.html
<html>

{% load static %}

<head>
	<meta charsef="utf-8">
    <meta name="viewport" content="width=device-width, initial scale=1">
	<title>Lidi -- Problem {{ problem.id }}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/header.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/html.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/content.css' %}" />
    <link rel="stylesheet" href="{% static 'css/highlight/default.css' %}">
    <script src="{% static 'js/highlight.pack.js' %}"></script>
</head>
<body>
	<div id="header">
        <div id="header-inner">
            <nav>
                <ul>
                    <li id="current"><a href="{% url 'home:index' %}">Home</a></li>
                    <li><a href="{% url 'problem:index' %}">Problems</a></li>
                    <li><a href="{% url 'statistics:index' %}">Statistics</a></li>
                    {% if user != None %}
                        <li><a href="{% url 'upload:upload' %}">Upload</a></li>
                        <li><a href="{% url 'login:logout' %}">Logout ({{ user }})</a></li>
                    {% else %}
                            <li><a href="{% url 'login:index' %}">Login</a></li>
                            <li><a href="{% url 'signup:index' %}">Sign Up</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
	<div id="page">
		<div id="content_problem">
			<div class="problem_name">
				<h2>Problem {{ problem.id }}: {{ problem.name }}</h2>
			</div>
			<div class="problem_desc">
				<p>{{ problem.desc }}</p>
			</div>
		</div>

		{% if user != None %}
			<div id="upload">
				<form enctype="multipart/form-data" method="POST">
					{% csrf_token %}
					{{ form }}
					<div class="g-recaptcha" data-sitekey="6LdXGyQUAAAAAB8JUpnvNLFJv0b36ygtg5Z1OrE3"></div>
					<input type="submit" value="Submit" id="submit_solution">
				</form>
			</div>

            {% if grade != -1 or l_grade != -1 or error != -1 %}
                <div id="submission">
                    <div id="parent_grades">
                        {% if grade != -1 %}
                            <div id="highest_grade" class="div_grade">
                                <p>Your highest grade: <b>{{ grade }}</b></p>
                            </div>
                        {% endif %}
                        {% if l_grade != -1 and error == -1 %}
                            <div class="div_grade last_{{ l_grade }}">
                                <p>You scored: <b>{{ l_grade }}</b></p>
                            </div>
                        {% elif error != -1 %}
                            <div class="div_grade error">
                                <p>Error: {{ error }}</p>
                            </div>
                        {% endif %}
                    </div>
                    {% if user_category == 1 %}
                        {% if out_time.0 != -1 or out_time.1 != -1 %}
                            <div id="parent_outputs">
                                {% if out_time.0 != -1 %}
                                    <div class="outputs">
                                        <h3>Last out</h3>
                                        <table class="table_outs">
                                            <tr>
                                                <th class="id">#</th>
                                                <th class="time">Time</th>
                                                <th class="outs">Output</th>
                                            </tr>
                                            {% for out in out_time.0 %}
                                                <tr>
                                                    <td class="id">
                                                        {{ forloop.counter }}
                                                    </td>
                                                    <td class="time">
                                                        {{ out.1 }}
                                                    </td>
                                                    <td class="outs">
                                                        <pre><code><span class="pre_span">{{ out.0 }}</span></code></pre>
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                        </table>
                                    </div>
                                {% endif %}
                                {% if out_time.1 != -1 %}
                                    <div class="outputs">
                                        <h3>Best out</h3>
                                        <table class="table_outs">
                                            <tr>
                                                <th class="id">#</th>
                                                <th class="time">Time</th>
                                                <th class="outs">Output</th>
                                            </tr>
                                            {% for out in out_time.1 %}
                                                <tr>
                                                    <td class="id">
                                                        {{ forloop.counter }}
                                                    </td>
                                                    <td class="time">
                                                        {{ out.1 }}
                                                    </td>
                                                    <td class="outs">
                                                        <pre><code><span class="pre_span">{{ out.0 }}</span></code></pre>
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                        </table>
                                    </div>
                                {% endif %}
                                <div style="clear: both;"></div>
                            </div>
                        {% endif %}
                        {% if out_time.3 != -1 %}
                            <div class="outputs">
                                <h3>Testcases</h3>
                                <table class="table_outs">
                                    <tr>
                                        <th class="id">#</th>
                                        <th class="ins">Testcase</th>
                                        <th class="outs">Solution</th>
                                    </tr>
                                    {% for out in out_time.3 %}
                                        <tr>
                                            <td class="id">
                                                {{ forloop.counter }}
                                            </td>
                                            <td class="ins">
                                                <pre><code><span class="pre_span">{{ out.0 }}</span></code></pre>
                                            </td>
                                            <td class="outs">
                                                <pre><code><span class="pre_span">{{ out.1 }}</span></code></pre>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </table>
                            </div>
                        {% endif %}
                        {% if out_time.2 != -1 %}
                            <div id="program" class="outputs">
                                <h3>Your last submission</h3>
                                <pre><code><span class="pre_span">{{ out_time.2 }}</span></code></pre>
                            </div>
                        {% endif %}
                    {% endif %}
                </div>
            {% endif %}
		{% else %}
			<div id="notify-signin">
				Sign in to upload your solution.
			</div>
		{% endif %}
	</div>
</body>

<script>hljs.initHighlightingOnLoad();</script>
<script src='https://www.google.com/recaptcha/api.js'></script>
</html>

lidi/problem/templates/problem/index.html
<html>

{% load static %}

<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial scale=1">
	<title>Lidi -- Problems</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/header.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/html.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/content.css' %}" />
</head>
<body>
	<div id="header">
        <div id="header-inner">
            <nav>
                <ul>
                    <li id="current"><a href="{% url 'home:index' %}">Home</a></li>
                    <li><a href="{% url 'problem:index' %}">Problems</a></li>
                    <li><a href="{% url 'statistics:index' %}">Statistics</a></li>
                    {% if user != None %}
                        <li><a href="{% url 'upload:upload' %}">Upload</a></li>
                        <li><a href="{% url 'login:logout' %}">Logout ({{ user }})</a></li>
                    {% else %}
                            <li><a href="{% url 'login:index' %}">Login</a></li>
                            <li><a href="{% url 'signup:index' %}">Sign Up</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>

	<div id="page">
		<div id="content">
			<div id="pagination">
				<span class="page_control">
					{% if problems.has_previous %}
						<a href="{% url 'problem:index' page=problems.previous_page_number sort_by='id' %}">Previous</a>
					{% else %}
						<a class="disabled">Previous</a>
					{% endif %}

					<span class="current_page">
						<b>{{ problems.number }}</b> / {{ problems.paginator.num_pages }}
					</span>

					{% if problems.has_next %}
						<a href="{% url 'problem:index' page=problems.next_page_number sort_by='id' %}">Next</a>
					{% else %}
						<a class="disabled">Next</a>
					{% endif %}
				</span>
			</div>
		</div>
		<div id="problems">
			<table>
				<tr>
					<th><a href="{% url 'problem:index' page=problems.number sort_by='id' %}">ID</a></th>
					<th><a href="{% url 'problem:index' page=problems.number sort_by='name' %}">Name</a></th>
					<th><a href="{% url 'problem:index' page=problems.number sort_by='difficulty' %}">Difficulty</a></th>
                    {% if user is not None %}
                        <th>Score</th>
                    {% endif %}
				<tr>
				{% for problem in problems %}
				<tr>
                    <td class="id"><a href="{% url 'problem:detail' problem.id %}">{{ problem.id }}</a></th>
					<td class="name"><a href="{% url 'problem:detail' problem.id %}">{{ problem.name }}</a></th>
					<td class="diff"><a href="{% url 'problem:detail' problem.id %}">{{ problem.difficulty }}</a></th>
                    {% if user is not None %}
                        {% if problem.user_grade != -1 %}
                            <td class="diff">{{ problem.user_grade }}</td>  <!-- TODO add different class -->
                        {% else %}
                            <td class="diff"></td>
                        {% endif %}
                    {% endif %}
				</tr>
			{% endfor %}
			</table>
		</div>
	</div>

	<div id="footer">
	</div>
</body>







</html>