lidi/home/urls.py
from django.conf.urls import url
from . import views


app_name = 'home'

urlpatterns = [
    # /problems/
    url(r'^$', views.index, name="index"),
]

lidi/lidi/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import TemplateView

app_name = 'lidi'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include('login.urls')),
    url(r'^problems/', include('problem.urls')),
    url(r'^upload/', include('upload.urls')),
    url(r'^signup/', include('signup.urls')),
    url(r'^statistics/', include('statistics.urls')),
    url(r'^', include('home.urls')),
]

lidi/login/urls.py
from django.conf.urls import url

from . import views

app_name = 'login'

urlpatterns = [
    # /login/
    url(r'^$', views.index, name="index"),

    # /login/out/
    url(r'^out/$', views.logout, name="logout"),

    # /login/reset_password/<conf_link>/
    url(r'^reset_password/(?P<conf_link>\d+)$', views.reset_password, name='reset_password'),

    # /login/reset_password/
    url(r'^reset_password/$', views.reset_password, name='reset_password')
]

lidi/problem/urls.py
from django.conf.urls import url

from . import views


app_name = 'problem'

urlpatterns = [
    # /problems/
    url(r'^$', views.index, name="index"),
    
    # /problems?page=<page>/
    url(r'^\\?page=(?P<page>[0-9]+)/$', views.index, name="index"),

    # /problems?page=<page>?sort=<sort_by>/
    url(r'^\\?page=(?P<page>[0-9]+)\\?sort=(?P<sort_by>[\s\S]+)/$', views.index, name="index"),

    # /problems/<problem_id>/
    url(r'^(?P<problem_id>[0-9]+)/$', views.detail, name="detail"),
]

lidi/signup/urls.py
from django.conf.urls import url

from . import views

app_name = 'signup'

urlpatterns = [
    # /signup/
    url(r'^$', views.index, name="index"),

    # /signup/confirm/<conf_link>/
    url(r'^confirm/(?P<conf_link>\d+)$', views.confirm, name='confirm'),
]

lidi/statistics/urls.py
from django.conf.urls import url

from . import views

app_name = 'statistics'

urlpatterns = [
    # /statistics/
    url(r'^$', views.index, name='index'),

    # /statistics/problem/
    url(r'^problem/$', views.problem, name='problem'),

    # /statistics/problem/<problem_id>/
    url(r'^problem/(?P<problem_id>\d+)/$', views.problem, name='problem_detail'),

    # /statistics/country/
    url(r'^country/$', views.country, name='country'),

    # /statistics/country/<country_slug>/
    url(r'^country/(?P<country_slug>[a-z_]+)/$', views.country, name='country_detail'),

    # /statistics/users/
    url(r'^users/$', views.users, name='users'),

    # /statistics/users/<username>
    url(r'^users/(?P<username>[0-9a-zA-Z_]+)/$', views.users, name='users_detail'),

    # /statistics/achievements/
    url(r'^achievements/$', views.achievements, name='achievements'),

    # /statistics/achievements/<achievement_id>/
    url(r'^achievements/(?P<achievement_id>\d+)/$', views.achievements, name='achievements_detail')
]

lidi/upload/urls.py
from django.conf.urls import url

from . import views

app_name = 'upload'

urlpatterns = [
    # /upload/
    url(r'^$', views.upload_file, name="upload"),
]

lidi/upload/forms.py
from django import forms

class UploadFileForm(forms.Form):
	f = forms.FileField(label="")

lidi/upload/views.py
from django.shortcuts import render

from .forms import UploadFileForm
from .support import handle_uploaded_file
import login


def upload_file(request):
    """
        Loads a page that provides ability for users to upload their problems.
        :param request
    """

    # If user is not logged in, set current user to None.
    try:
        request.session['user']
    except KeyError:
        request.session['user'] = None

    # If user is not logged in, redirect to login page.
    if request.session['user'] is None:
        return login.views.index(request, 'upload')

    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            file_ok = handle_uploaded_file(request.FILES['f'])
            request.FILES['f'] = None
            if file_ok:
                return render(request, 'upload/upload.html', {'form': form, 'user': request.session['user'], 'msg': 1})
            else:
                return render(request, 'upload/upload.html', {'form': form, 'user': request.session['user'], 'msg': 0})
    else:
        form = UploadFileForm()

    return render(request, 'upload/upload.html', {'form': form, 'user': request.session['user'], 'msg': -1})

lidi/upload/templates/upload/upload.html
<html>

{% load static %}

<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial scale=1">
	<title>Lidi -- Upload a problem</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/html.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/header.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/content.css' %}" />
</head>
<body>
    <div id="header">
        <div id="header-inner">
            <nav>
                <ul>
                    <li id="current"><a href="{% url 'home:index' %}">Home</a></li>
                    <li><a href="{% url 'problem:index' %}">Problems</a></li>
                    <li><a href="{% url 'statistics:index' %}">Statistics</a></li>
                    {% if user != None %}
                        <li><a href="{% url 'upload:upload' %}">Upload</a></li>
                        <li><a href="{% url 'login:logout' %}">Logout ({{ user }})</a></li>
                    {% else %}
                        <li><a href="{% url 'login:index' %}">Login</a></li>
                        <li><a href="{% url 'signup:index' %}">Sign Up</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>

	<div id="page">
		<div id="content">
			<div id="upload_text">
				<h2>Uploading problems</h2>
				<h3>Rules</h3>
				<p>The rules are simple. You submit a problem in an archive (either .zip or .tar.gz, although others are OK as well). Preferably name an archive with problem name (you can use spaces in filename). Otherwise the name of problem will be chosen by admins. Each problem archive must contain:</p>
				<ul>
					<li>A file with task styled with markdown and MathJax.</li>
					<li>Ten (10) testcase files. Each testcase can have subtasks but must be included in same file.</li>
					<li>Ten (10) testcase solution files.</li>
					<li>A file with memory and time limits. The file should look like this: <code>memory=128; time=2</code>. You can insert any spaces you like, just keep it in one line and separate memory from time with semicolon. The example given means that a program can use at most 128MiB of memory and can run for at most 2 seconds.</li>
				</ul>
				<p>If you want to upload multiple tasks at once, you can do that by including problem archives into one master archive, just make sure the archive does not excede the upload limit of 10MB. Also name that file "master", e.g. "master.tar.gz".</p>
			</div>
			<div id="upload">
				<div id="form">
					<form enctype="multipart/form-data" method="POST">
						{% csrf_token %}
						{{ form }}
						<div class="g-recaptcha" data-sitekey="6LdXGyQUAAAAAB8JUpnvNLFJv0b36ygtg5Z1OrE3"></div>
						<input type="submit" value="Upload">
					</form>
					{% if msg == 1 %}
						<p class="error">File uploaded successfully, thanks!</p>
					{% elif msg == 0 %}
						<p class="error">Uploaded file is either not a valid archive or it excedes 10MB.</p>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
</body>

<script src='https://www.google.com/recaptcha/api.js'></script>
</html>