lidi/home/urls.py
from django.conf.urls import url
from . import views


app_name = 'home'

urlpatterns = [
    # /problems/
    url(r'^$', views.index, name="index"),
]

lidi/lidi/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import TemplateView

app_name = 'lidi'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include('login.urls')),
    url(r'^problems/', include('problem.urls')),
    url(r'^upload/', include('upload.urls')),
    url(r'^signup/', include('signup.urls')),
    url(r'^statistics/', include('statistics.urls')),
    url(r'^', include('home.urls')),
]

lidi/login/urls.py
from django.conf.urls import url

from . import views

app_name = 'login'

urlpatterns = [
    # /login/
    url(r'^$', views.index, name="index"),

    # /login/out/
    url(r'^out/$', views.logout, name="logout"),

    # /login/reset_password/<conf_link>/
    url(r'^reset_password/(?P<conf_link>\d+)$', views.reset_password, name='reset_password'),

    # /login/reset_password/
    url(r'^reset_password/$', views.reset_password, name='reset_password')
]

lidi/signup/urls.py
from django.conf.urls import url

from . import views

app_name = 'signup'

urlpatterns = [
    # /signup/
    url(r'^$', views.index, name="index"),

    # /signup/confirm/<conf_link>/
    url(r'^confirm/(?P<conf_link>\d+)$', views.confirm, name='confirm'),
]

lidi/login/models.py
from django.db import models

lidi/login/forms.py
from django import forms


class LoginForm(forms.Form):
    user = forms.CharField(label="", help_text="", max_length=20, widget=forms.TextInput(attrs={'placeholder': 'Username or email'}))
    password = forms.CharField(label="", help_text="", max_length=16, widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))


class PasswordResetEmailForm(forms.Form):
    user = forms.CharField(label="", help_text="", max_length=20, widget=forms.TextInput(attrs={'placeholder': 'Username or email'}))


class PasswordResetChangePasswordForm(forms.Form):
    username = forms.CharField(label="", help_text="", max_length=20, widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    password1 = forms.CharField(label="", help_text="", max_length=16, widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    password2 = forms.CharField(label="", help_text="", max_length=16, widget=forms.PasswordInput(attrs={'placeholder': 'Repeat password'}))

lidi/login/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from .forms import LoginForm, PasswordResetEmailForm, PasswordResetChangePasswordForm
from .support import validate_login, send_reset_password, validate_reset_link, reset_pwd
from lidi.settings import BASE_HTTP_ADDRESS


def index(request, error=None):
    """
        Load login page.
        :param request
        :param error: denotes if there was some wrong try while trying to log in
    """

    # If user is already logged in, we do not need to log him in.
    try:
        if request.session['user'] is not None:
            return redirect(BASE_HTTP_ADDRESS)
    except KeyError:
        pass  # continue with logging in

    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = form.cleaned_data['user']
            pwd = form.cleaned_data['password']
            username = validate_login(user, pwd)
            if username:
                request.session['user'] = username
                return redirect(BASE_HTTP_ADDRESS)
            else:
                return render(request, 'login/index.html', {'form': form, 'valid': False, 'error': error})
    else:
        form = LoginForm()

    return render(request, 'login/index.html', {'form': form, 'valid': True, 'error': error})


def logout(request):
    """
        Logs user out just by setting current user to None.
        :param request
    """

    request.session['user'] = None
    return redirect(BASE_HTTP_ADDRESS)


def reset_password(request, conf_link=None):
    """
        If conf_link is None, serve page where user can reset password.
        If conf_link is set, provide the possibility to enter new password.
        :param request
        :param conf_link: if present, user has clicked the link, else default page
    """

    # User has to enter email or username.
    if conf_link is None:
        if request.method == 'POST':
            form = PasswordResetEmailForm(request.POST)
            if form.is_valid():
                if send_reset_password(form.cleaned_data['user']):
                    return HttpResponse('Check your email for password reset link')
                else:
                    return HttpResponse('Oops, something went wrong, please try again')
        else:
            form = PasswordResetEmailForm()
        return render(request, 'login/reset_index.html', {'form': form})

    # User has clicked on a reset password link in email.
    if validate_reset_link(conf_link):
        if request.method == 'POST':
            form = PasswordResetChangePasswordForm(request.POST)
            if form.is_valid():
                if form.cleaned_data['password1'] == form.cleaned_data['password2']:
                    if reset_pwd(form.cleaned_data['username'], form.cleaned_data['password1'], conf_link):
                        return HttpResponse('Password has been reset')
                    else:
                        return render(request, 'login/reset_index.html', {'form': form, 'error': 2})
                else:
                    return render(request, 'login/reset_index.html', {'form': form, 'error': 1})
        else:
            form = PasswordResetChangePasswordForm()
        return render(request, 'login/reset_index.html', {'form': form, 'error': 0})

    # Wrong conf_link.
    return HttpResponse('Wrong reset password link')

lidi/login/templates/login/index.html
<html>

{% load static %}

<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial scale=1">
	<title>Lidi -- Login</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/html.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/content.css' %}" />
</head>
<body>
	<div id="page">
		<div id="content">
			<div id="login_logo">
				<h1>LIDI</h1>
				<p>Log in</p>
				{% if error == 'upload' %}
					<p class="error">You must log in to upload problems.</p>
				{% endif %}
			</div>
			<div id="login_form">
				<form method="POST">
					{% csrf_token %}
					{{ form }}
					<input type="submit" value="Login">
                    <input type="button" value="Forgot password?" onclick="location.href = '{% url 'login:reset_password' %}';">
                    <input type="button" value="Sign up" onclick="location.href = '{% url 'signup:index' %}';">
					<input type="button" value="Home" onclick="location.href = '{% url 'home:index' %}';">
				</form>
				{% if not valid %}
					<p class="error">Invalid (username, password) combination.</p>
				{% endif %}
			</div>
		</div>
	</div>
</body>



</html>

lidi/login/templates/login/reset_index.html
<!DOCTYPE html>

{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial scale=1">
    <title>Lidi -- Reset Password</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/html.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/content.css' %}" />
</head>

<body>
    <div id="page">
        <div id="login_logo">
            <h1>LIDI</h1>
            <p>RESET PASSWORD</p>
        </div>

		<div id="content">
            <div id="login_form">
                <form method="POST">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" value="Confirm">
                    <input type="button" value="Home" onclick="location.href = '{% url 'home:index' %}';">
                </form>
                {% if error == 1 %}
                    <p class="error">Passwords do not match.</p>
                {% elif error == 2 %}
                    <p class="error">Wrong username for given confirmation link.</p>
                {% endif %}
            </div>
        </div>
    </div>
</body>

</html>